from typing import Any, Dict

from .util import create_ticker


def get_stock_dcf_analysis(symbol: str) -> Dict[str, Any]:
    """Generate a structured Discounted Cash Flow (DCF) valuation for a stock.

    Delegates the full computation to ``Ticker.dcf_data()`` and returns its
    result verbatim. No Excel file is opened or generated by this tool — the
    caller (e.g. a downstream skill) is responsible for any spreadsheet
    rendering.

    Args:
        symbol (str):
            Stock ticker symbol (case-insensitive).
            Examples: "AAPL", "TSLA", "MSFT", "GOOGL"

    Returns:
        dict: On success, the structured DCF analysis produced by
        ``Ticker.dcf_data()``. Top-level keys:

            - symbol (str): Normalized ticker symbol (uppercase).
            - discount_rate (dict): WACC inputs and computed values
              (market_cap, beta_5y, total_debt, interest_expense,
              pretax_income, tax_provision, risk_free_rate,
              expected_market_return, weight_of_debt, weight_of_equity,
              cost_of_debt, cost_of_equity, tax_rate, wacc, report_date).
            - growth_estimates (dict): Historical growth context.
                - currency (str): Reporting currency (e.g. "USD").
                - revenue: {details: [{date, value, yoy} x3], cagr_3y}.
                - eps: {details: [{date, value, yoy} up to 10],
                  cagr_10y, cagr_years}.
                - treasury: {details: [{year, avg_yield}], avg_5y}.
            - dcf_template (dict): Assumptions, 10-year projections, and
              historical FCF margin.
                - growth_rate_1_5y, growth_rate_6_10y,
                  growth_rate_terminal, discount_rate.
                - ttm_revenue, ttm_revenue_label, ttm_period, base_fcf,
                  end_date.
                - revenue_growth_1_5y, revenue_growth_6_10y.
                - projections: 11 entries indexed by year. ``year=0`` is the
                  TTM base (terminal_value=0); ``year=1..10`` are forecasts.
                  ``terminal_value`` is non-zero only at ``year=10``.
                  Each entry has {year, date, fcf, terminal_value,
                  total_value, fcf_margin}.
                - historical_fcf_margin: up to 5 {date, margin} entries.
            - dcf_value (dict): Valuation conclusion
              (enterprise_value, cash, total_debt, equity_value,
              shares_outstanding, fair_price, current_price,
              margin_of_safety, recommendation, report_date).
              ``recommendation`` is "Buy" or "Sell".

        On failure, ``{"symbol": <SYMBOL>, "error": <message>}``.

    Example Success Response (abridged):
        {
            "symbol": "AAPL",
            "discount_rate": {"wacc": 0.13, ...},
            "growth_estimates": {
                "currency": "USD",
                "revenue": {"details": [...], "cagr_3y": 0.042},
                "eps": {"details": [...], "cagr_10y": 0.162, "cagr_years": 9},
                "treasury": {"details": [...], "avg_5y": 0.035}
            },
            "dcf_template": {
                "growth_rate_1_5y": 0.162,
                "growth_rate_6_10y": 0.137,
                "growth_rate_terminal": 0.035,
                "projections": [{"year": 0, ...}, ..., {"year": 10, ...}],
                "historical_fcf_margin": [...]
            },
            "dcf_value": {
                "fair_price": 180.51,
                "current_price": 293.32,
                "margin_of_safety": -0.62,
                "recommendation": "Sell"
            }
        }
    """
    symbol = symbol.upper()

    try:
        ticker = create_ticker(symbol)
        return ticker.dcf_data()
    except ValueError as e:
        # dcf_data() raises ValueError when required inputs (e.g. WACC) are
        # unavailable — typically for ETFs, indices, or tickers without
        # financial statements.
        return {"symbol": symbol, "error": str(e)}
    except Exception as e:
        return {
            "symbol": symbol,
            "error": f"Error generating DCF analysis: {str(e)}",
        }
